name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path:  |
            requirements.txt
            requirements_test.txt
      - name: Set up headless display
        uses: pyvista/setup-headless-display-action@v2
      - name: Install PyVista
        run: pip install . --no-deps
      - name: Install test dependencies
        run: pip install vtk -r requirements_test.txt
      - name: Cache example data
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pyvista/examples
          key: Examples-1-${{ hashFiles('*') }}
          restore-keys: |
            Examples-1-
      - name: Install pvplanets
        run: pip install -e .
      - name: Run Tests
        run: |
          pytest
